### PR TITLE
Update AutoSave

### PR DESCRIPTION
**Pull request by ColonelGerdauf**
The AutoSave plugin was updated a few times via GitHub, and yet was never updated on the NP++ list.

### CODE REVIEW

**Comment by ColonelGerdauf** [comment]
It should be noted that the version that was written has a major nuisance bug where in specific situation it can cause the Notepad++ program to effectively hang until a prolonged saving process.

The versions after - not updated in N++ - have resolved this issue.

**Comment by chcg** [comment]
@ColonelGerdauf The update of the markdown files is not necessary. They are updated from json input on releases.
See missing update of id aka sha256 hash of the zip package:
https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/46221851/job/b6rsd3fdsi6xhunx/messages
https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/46221851/job/2wbx60kk0jixm7ke/messages

**Comment by chcg** [comment]
@francostellari Is it ok for you to update to V2.0?

**Comment by francostellari** [comment]
I'm ok if you want to upgrade to v2.00.
As mentioned there are significant changes that may make some people happy and other unhappy.

v2.00
Major code rework breaking previous features

Removed: various file checking features to simplofy the behavior
Fix: tab flipping to save only named files
Added: save on tab change feature
Added: save on Notepad++ exit

**Pull request merged**
