### PR TITLE
Validator updates

### PR DESCRIPTION
**Pull request by dail8859**
Adds quite a few checks to the validator

### CODE REVIEW

**Comment by dail8859** [comment]
Hmm...looks like appveyor might default to a version of Python that doesn't support f strings...will look into it when I get a chance.

**Comment by chcg** [comment]
See https://github.com/bycn82/visimulator/issues/1, known issue that version infos is missing

**Comment by dail8859** [comment]
Is a valid version number *required* by N++ and/or GUP?

Either the plugin would need removed from this list, or else the check of a matching version number isn't needed.

**Comment by chcg** [comment]
@dail8859 For PM the version info of the plugin dll was needed/checked, but PA just checks the sha256 and also to show the installed plugins the version info seems to be not checked. So it might be relevant for the future, but currently it is not a required check, but good to know.

**Comment by dail8859** [comment]
According to the [Notepad++ Website](https://notepad-plus-plus.org/features/plugin-admin.html)

> 4. Update info: the value of "version" is exact the version of your plugin binary version which you want to be deployed. This version will compare with installed plugin's version to decide if update should be applied. Please check [Microsoft's document about binary version](https://docs.microsoft.com/en-us/windows/desktop/menurc/versioninfo-resource) for setting the version correctly onto your DLL.

**Comment by chcg** [comment]
@dail8859 Maybe there is no problem for the initial installation. On checking the VI Simulator installation just the version from the list is displayed, also the dll itself doesn't contain a version number.

**Comment by dail8859** [comment]
Correct. So is the version information used for updating it though since it will have to check the DLL version to determine if an update is available?

**Comment by dinkumoil** [comment]
Point 4. of the [_Rules for adding your plugins into list_](https://notepad-plus-plus.org/features/plugin-admin.html) states that the version info is required for updating a plugin.

That means a plugin without version infos in its DLL never gets updated. It means also that it is not recommended any more to write plugins with a programming language which is not able to include version infos in the DLL.

**Pull request merged**
