### PR TITLE
New Release 5.3.24 of SQLinForm

### PR DESCRIPTION
**Pull request by guidomarcel**
New Release 5.3.24 of SQLinForm

### CODE REVIEW

**Comment by chcg** [comment]
@guidomarcel See the diff, the complete file is changed probably some tab -> space issue. Could you correct that. Otherwise I would do a manual merge of the change.

**Comment by guidomarcel** [comment]
Hi,I guess I cannot correct this as I used the Web github feature and I do not know how to avoid this tab / space issue. Would you mind doing the merge manually?Many thanks Guido 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: chcg <notifications@github.com> Datum: 11.01.19  00:02  (GMT+01:00) An: notepad-plus-plus/nppPluginList <nppPluginList@noreply.github.com> Cc: guidomarcel <guido.thelen@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [notepad-plus-plus/nppPluginList] New Release 5.3.24 of SQLinForm (#49) 
@guidomarcel See the diff, the complete file is changed probably some tab -> space issue. Could you correct that. Otherwise I would do a manual merge of the change.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/notepad-plus-plus/nppPluginList","title":"notepad-plus-plus/nppPluginList","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/notepad-plus-plus/nppPluginList"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chcg in #49: @guidomarcel See the diff, the complete file is changed probably some tab -\u003e space issue. Could you correct that. Otherwise I would do a manual merge of the change."}],"action":{"name":"View Pull Request","url":"https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-453290880"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-453290880",
"url": "https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-453290880",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by guidomarcel** [comment]
Hi, I tried again to edit the json file. When I click the Edit button the following message is being displayed:

> We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF)

Probably this is the reason for the issue. Any suggestions what I could do?

Thanks & Regards
Guido

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/nppPluginList/commit/883e365cff518c8d8f7be263601b3716b9d294c8

**Comment by guidomarcel** [comment]
Hi,

any idea when the new version will be available for download?

Regards

Guido

 

Von: chcg <notifications@github.com> 
Gesendet: Freitag, 11. Januar 2019 22:12
An: notepad-plus-plus/nppPluginList <nppPluginList@noreply.github.com>
Cc: guidomarcel <guido.thelen@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [notepad-plus-plus/nppPluginList] New Release 5.3.24 of SQLinForm (#49)

 

Closed #49 <https://github.com/notepad-plus-plus/nppPluginList/pull/49> .

**Comment by chcg** [comment]
@guidomarcel Mixture was introduced with https://github.com/notepad-plus-plus/nppPluginList/commit/641684141ea201dc54d390699bf6b24c78f6a999, corrected in the meantime. Thanks for the hint.

Do you want to provide also a 64bit version of Release 5.3.24? Otherwise I would create a tag right now and then donho has to take over.

**Comment by guidomarcel** [comment]
I prefer publishing the 64 bit version only next week. Happy if you create a tag.ThisGuido


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: chcg <notifications@github.com> Datum: 19.01.19  12:31  (GMT+01:00) An: notepad-plus-plus/nppPluginList <nppPluginList@noreply.github.com> Cc: guidomarcel <guido.thelen@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [notepad-plus-plus/nppPluginList] New Release 5.3.24 of SQLinForm (#49) 
@guidomarcel Mixture was introduced with 6416841, corrected in the meantime. Thanks for the hint.
Do you want to provide also a 64bit version of Release 5.3.24? Otherwise I would create a tag right now and then donho has to take over.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/notepad-plus-plus/nppPluginList","title":"notepad-plus-plus/nppPluginList","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/notepad-plus-plus/nppPluginList"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chcg in #49: @guidomarcel Mixture was introduced with https://github.com/notepad-plus-plus/nppPluginList/commit/641684141ea201dc54d390699bf6b24c78f6a999, corrected in the meantime. Thanks for the hint.\r\n\r\nDo you want to provide also a 64bit version of Release 5.3.24? Otherwise I would create a tag right now and then donho has to take over."}],"action":{"name":"View Pull Request","url":"https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-455772228"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-455772228",
"url": "https://github.com/notepad-plus-plus/nppPluginList/pull/49#issuecomment-455772228",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by chcg** [comment]
@donho See https://github.com/notepad-plus-plus/nppPluginList/releases/tag/v1.0.5

**Pull request closed without merging**
