### PR TITLE
Fix version

### PR DESCRIPTION
**Pull request by snxx-lppxx**
Changed `resource.h`.

### CODE REVIEW

**Comment by chcg** [comment]
grafik

**Comment by snxx-lppxx** [comment]
image
if I'm not mistaken, then the version is incorrectly written

**Comment by snxx-lppxx** [comment]
Something went wrong. Made through tabs.

**Comment by chcg** [comment]
@snxx-lppxx Thanks for spotting this and the providing of the PR.

**Comment by chcg** [comment]
@donho N++ has the same behavior, see

grafik

Want we also correct it there?

**Comment by donho** [comment]
It's intentional to have 7.94 - it's the way that Notepad++ versioning though it's not a conventional way.
For comparing the version to learn which one is newer, between 2 versions, the first numbers before the first point are compared, if equal, then the 2nd parts after point are compared. 
See:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/resource.h#L24

OTOH, the 2nd part is limited on 2 digits.

Though the plugin list is not applied yet to update system, I would like to keep the same system.
Could this merge be reverted please?

**Pull request merged**
