### PR TITLE
Added Linefilter3 to the plugin list (x64 & x86)

### PR DESCRIPTION
**Pull request by SeeliSoft-CH**
Created Linefilter3 plugin, to be added to x64 & x86 plugin list

### CODE REVIEW

**Comment by chcg** [comment]
@SeeliSoft-CH Is the released x64 version working for you. During my test with N++ 7.7.1 and 7.7.0 this version couldn't be loaded. The x86 version is working fine.

**Comment by SeeliSoft-CH** [comment]
@chcg I tested again the x64 version with N++ 7.7.1 (zip / portable version) on Win 7 and Win 10.
Plugin x64

does the sha2 hash match with the downloaded/installed file?

**Comment by chcg** [comment]
Still not working for me. Sha256 is ok. Maybe some issue with my computer and .net. Anyhow added the plugin to the list and let's see, if such an issue gets reported.

**Comment by SeeliSoft-CH** [comment]
Many thanks

**Comment by SeeliSoft-CH** [comment]
You were right, there is indeed some issue with Windows 10. I found a more recent .NET template and fixed the issue. But since the SHA2 hash has changed, I'll need to create a new pull request.

**Pull request merged**
