### PR TITLE
Add XMLTools entry for x64 version

### PR DESCRIPTION
**Pull request by morbac**

### CODE REVIEW

**Comment by donho** [comment]
@chcg there's an error of python script - however both files are valid json file.
Could you check it please?

**Comment by chcg** [comment]
@donho This not an issue of this PR, but I just havn't made a decision how to handle plugins with missing version infos in the dll, see https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/20547399/job/8y97v87qjxrj2f3h/messages.
Without version info each installed dll of that plugin will be reported to be the latest one and updates will never been offered.

**Comment by donho** [comment]
@chcg 
> Without version info each installed dll of that plugin will be reported to be the latest one and updates will never been offered.

Good point +1
So the python script download the zip, unzip it, then check the binary version? Because all I see is appveyor's error.

**Comment by chcg** [comment]
Yes, thanks to @dail8859 the python script is capable to download the zip, verify that the zip is valid, hash is ok and version info is available and as expected.

My current feeling is to remove such plugins from the list or have something like in PM that the stability of such plugins is limited and the user has to explicitly enable an option for the visibility or at least acknowledge that he knows about the limitations and anyhow wants that plugin to be installed.

**Pull request merged**
