### PR TITLE
added nppftp 0.27.5 with corrected SHA-256 checksums

### PR DESCRIPTION
**Pull request by chcg**
Correction for #3

### CODE REVIEW

**Comment by chcg** [comment]
- Would be nice to have the expected vs current checksum in case of a mismatch.
- extend md5 tool in n++ to also support sha-256

**Comment by chcg** [comment]
See https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins64.xml

	```
Line 42: 				<copy from="AnalysePlugin\x64\AnalysePlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 63: 				<copy from="Win64\AutoCodepage.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 82: 				<copy from="Win64\AutoEolFormat.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 105: 				<copy from="64bit\AutoSave.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 119: 				<copy from="BetterMultiSelection_64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 159: 				<copy from="CodeAlignmentNpp.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 186: 				<copy from="CodeStats.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 200: 				<copy from="ComparePlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 219: 				<copy from="NppConverter\NppConverter.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 240: 				<copy from="plugins\CSScriptNpp.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 260: 				<copy from="CsvQuery.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 292: 				<copy from="Win64\CustomLineNumbers.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 312: 				<copy from="DoxyIt_64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 332: 				<copy from="DSpellCheck.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 346: 				<copy from="ElasticTabstops_64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 382: 				<copy from="ImgTag.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 399: 				<copy from="JsMapParser.NppPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 414: 				<copy from="[Notepad++ Directory]\plugins\jN.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 433: 				<copy from="NPPJSONViewer.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 456: 				<copy from="JSMinNPP.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 473: 				<copy from="64bit\LanguageHelp.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 487: 				<copy from="LuaScript_64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 512: 				<copy from="MarkdownViewerPlusPlus.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 537: 				<copy from="64bit\MenuIcons.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 552: 				<copy from="mimeTools\mimeTools.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 583: 				<copy from="bin64\NavigateTo.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 602: 				<copy from="bin64/NotepadSharp.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 622: 				<copy from="NppBplistPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 638: 				<copy from="NotepadStarterPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 667: 				<copy from="NppXmlTreeviewPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 695: 				<copy from="npp.connections.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 714: 				<copy from="nppcrypt.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 732: 				<copy from="NppEventExec.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 748: 				<copy from="NppExec.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 772: 				<copy from="NppFavorites.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 789: 				<copy from="bin\NppFTP.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 839: 				<copy from="NppDocShare.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 853: 				<copy from="NppQrCode64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 872: 				<copy from="NppRegExTractorPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 898: 				<copy from="64bit\OpenSelection.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 913: 				<copy from="plugins\PluginManager.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 929: 				<copy from="PoorMansTSqlFormatterNppPlugin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 963: 				<copy from="pork2sausage\pork2sausage.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 979: 				<copy from="plugins\PythonScript.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1003: 				<copy from="64bit\RunMe.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1017: 				<copy from="NppSaveAsAdmin.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1030: 				<copy from="SelectNLaunch\SelectNLaunch.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1065: 				<copy from="NppSnippets.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1085: 				<copy from="SQLinFormNpp64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1104: 				<copy from="SurroundSelection_64.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1123: 				<copy from="TagLEET.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1146: 				<copy from="64bit\TakeNotes.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1160: 				<copy from="NppTaskList.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1175: 				<copy from="NppToolBucket.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1192: 				<copy from="64bit\TopMost.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1210: 				<copy from="ViSimulator.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1222: 				<copy from="XBrackets.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1243: 				<copy from="XMLTools.dll" to="$PLUGINDIR$\" validate="true"/>
	Line 1263: 				<copy from="zoomdisabler_x64.dll" to="$PLUGINDIR$\" validate="true"/>

```

most of the plugins are at the top level of the zip files. Might it be possible to check that and create a extra dir on the fly? What do you think.

**Comment by pnedev** [comment]
> Might it be possible to check that and create a extra dir on the fly?

That is a very good idea because all older plugins that already have their zip package somewhere will be useless - they'll need to be re-archived.

**Comment by chcg** [comment]
Updated PR and zip files to new structure with dll in root of zip and id as checksum of the zipfile.

**Comment by donho** [comment]
@chcg
> most of the plugins are at the top level of the zip files. Might it be possible to check that and create a extra dir on the fly? What do you think.

Good idea to me.

**Comment by donho** [comment]
047a772ee42ba73c198b7009be943265ed400ba7
Sorry for loosing the original author in my push. I did just a conflict resolve locally.
Will find a way to solve conflict correctly.

**Pull request closed without merging**
