### PR TITLE
Introduce a new plugin NX ASCII Database Helper

### PR DESCRIPTION
**Pull request by ZhuXuefengGitHub**
Hi Team, I would like to add a new plugin to Notepad++ plugin list. This plugin is created for the ASCII library data of Siemens NX CAM.  It includes two functionalities in the menu list:

image

- Format Database: Align the data of each CLASS with its corresponding attribute in format line.

image

- Show Class: Create a dialog box, extract the name of each type and show the number of items in type, and implement a jump to the corresponding row after clicking on the class name.

image

### CODE REVIEW

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/nppPluginList/actions/runs/9905849028/job/27419611001?pr=784

Version issue:

NX ASCII Database Helper
{'category': 'error',
 'details': '',
 'message': 'NX ASCII Database Helper: Unexpected DLL version. The DLL version '
            'detected is 4.3.0.0, but the expected version is 1.0.0.0.'}

**Comment by ZhuXuefengGitHub** [comment]
> See https://github.com/notepad-plus-plus/nppPluginList/actions/runs/9905849028/job/27419611001?pr=784
> 
> Version issue:
> 
> NX ASCII Database Helper {'category': 'error', 'details': '', 'message': 'NX ASCII Database Helper: Unexpected DLL version. The DLL version ' 'detected is 4.3.0.0, but the expected version is 1.0.0.0.'}
> 
> See https://github.com/ZhuXuefengGitHub/NX_ASCII_Database_Helper/blob/main/src/NppPluginDemo.rc#L23

Hi, I have modified the code and completed the update of the DLL file, thanks.

**Comment by ZhuXuefengGitHub** [comment]
> https://github.com/ZhuXuefengGitHub/NX_ASCII_Database_Helper/releases/download/v1.0.0/NX_ASCII_Database_Helper1.0.0.x64.zip contains dll twice. The entry here needs to be update also as the checksum changed.

Sorry for this, this issue has been resolved, and the "files changed" has been update as the checksum changed.

**Comment by ZhuXuefengGitHub** [comment]
> @ZhuXuefengGitHub Is there a specific reason to not provide x86 and arm64 versions of your plugin?

This will be implemented in the next version.

**Pull request merged**
