### PR TITLE
Added "Automation Scripts" (NppScripts) plugin

### PR DESCRIPTION
**Pull request by oleg-shilo**
Added "Automation Scripts" (NppScripts) plugin that has been ported to x64 platform

### CODE REVIEW

**Comment by gurikbal** [comment]
replace `"repository": "https://github.com/oleg-shilo/scripts.npp/releases/download/v2.0.0.0-beta/NppScripts.x64.zip",`
with `"repository": "https://github.com/oleg-shilo/scripts.npp/releases/download/v2.0.0.0/NppScripts.x64.zip",`

**Comment by chcg** [comment]
@oleg-shilo See above path needs to be adapted. Could the x86 version also be added?

**Comment by oleg-shilo** [comment]
My apologies. Truly silly mistake. 

Before creating PR I did properly test it with `nppPluginList.json`. And only after the PR was done I have decided to rename the Release in github from beta to normal. Since I was happy with the test results. And ... of course I broke the `nppPluginList.json` by doing that.

Anyway, it's fixed now. 

I have also added x86 version of the plugin even though I am not sure x86 N++ is still in use.

Thank you for looking into it.

**Comment by chcg** [comment]
@oleg-shilo I'm quite sure x86 is still in use. There are still some requests to support WinXP these days.
Thanks for the correction.

**Pull request merged**
