### PR TITLE
Update DSpellCheck to 1.4.21

### PR DESCRIPTION
**Pull request by Predelnik**

### CODE REVIEW

**Comment by chcg** [comment]
Appveyor failure is not due to this change.

**Comment by chcg** [comment]
@Predelnik Have you thought about an arm64 version of your plugin as N++ is supporting it since version 8 ? Maybe the dependent spell checkers might be a problem.

**Comment by Predelnik** [comment]
@chcg That's interesting. Is there any way to test it? If building is done through msvc there should not be any problem with it, as far as I can tell.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5158 I think you could request testing support from the guys who did the testing for N++.

**Comment by Predelnik** [comment]
Well alright, I guess I could just start by trying to build it first then. It's a bit sad that there is no cloud based testing environment somewhere at least, I could afford raspberry pi mentioned but don't know if I would have any other purpose for it :)

**Pull request merged**
