### PR TITLE
Update Elastic Tabstops to version 1.5.0

### PR DESCRIPTION
**Pull request by mariusv-github**
Update Elastic Tabstops to version 1.5.0 for x86 and x64 code.

### CODE REVIEW

**Comment by chcg** [comment]
@mariusv-github @dail8859 Is this a official handover of the plugin? Otherwise I would prefer to add a separate entry for the fork.

**Comment by dail8859** [comment]
Not an officially coordinated handover. But I'm certainly not against someone creating their own fork of the project.

My free time, interest, and personal need for the plugin is quite lacking lately. So I'd be willing to add users as admins to the repo if they'd like to help maintain it. That way updates can keep coming from the same place for now. And if later on someone wants to fully own it then we can definitely work something out.

**Comment by dail8859** [comment]
After looking deeper into it there are indeed quite alot of changes and enhancements where are good to see. I do appreciate the effort you have put in.

So I'm really open to whatever. In my opinion, I don't think there needs to be **two** versions of the plugin in the plugin list, that just causes confusion. If I ever do find an interest again in the plugin I don't foresee it going in a radically different direction.

(I was typing this as you responded.)

I was going to make these two proposals:

1. Add @mariusv-github as an admin to my repository and have full control to do whatever. Integrate changes/enhancements, publish releases, etc.
1. Archive my repository and we can all have a gentleman's agreement that @mariusv-github's repository is the "official" Elastic Tabstops plugin.

Then I saw:

> I prefer to use my own repo on Github and it's simpler for me to support it.

If that is the case (sounds like option 2) I'm fine archiving my repository and directing users to your repository as the "official" Elastic Tabstops plugin for Notepad++. @mariusv-github This kind of what you had in mind?

**Comment by mariusv-github** [comment]
Thank you again for your answer Justin.

> If that is the case (sounds like option 2) I'm fine archiving my repository and directing users to your repository as the "official" Elastic Tabstops plugin for Notepad++. @mariusv-github This kind of what you had in mind?

Yes. Like you, I do not see any reason to multiply the number of entries like "Elastic Tabstops Bis" or "Elastic Tabstops Enhanced", this can be confusing for normal users. In my personal case, we continue to use in our classrooms the Justin's version 1.3 with old NPP versions like 7.5 and the new version 1.5 with the current version of NPP. The new format of nppPluginList.json and nppPluginList.dll allow us to keep "old-versions-compatibility" for 1.3 version and add version 1.5 for post 2GB+ compatibility.

**Comment by rdipardo** [comment]
@mariusv-github,
> The new format of nppPluginList.json and nppPluginList.dll allow us to keep "old-versions-compatibility" for 1.3 version

I'm curious to know how that's supposed to work exactly.

The JSON metadata is only useful when the Notepad++ *editor* can actually *read* it.

The first version with the code to read the `"old-versions-compatibility"` property was 8.3.3: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a84cbe8f695e395e4eafb39158c7fc870403fe31

Take this rule for example:

~~~json
"old-versions-compatibility": "[,1.3][,8.2.1]"
~~~

Notepad++ 8.2.1 does not have the code to read this information.

The only benefit is for *newer* N++ versions (>= 8.3.3), which *can* read this information, and can realize that 8.2.1 is older than themselves.

If you took an old N++ version (e.g. 7.5), and you put a recently built `nppPluginList.dll` inside that installation's `plugins\Config` directory, the `"old-versions-compatibility"` information would be completely ignored, assuming the DLL is even loaded (since published DLLs are supposed to be digitally signed).

**Comment by dail8859** [comment]
All, FYI I've archived my ElasticTabstops repo and redirected users to @mariusv-github's repo.

https://github.com/dail8859/ElasticTabstops

**Comment by chcg** [comment]
@mariusv-github Are you interested in CI via github actions, see https://github.com/dail8859/ElasticTabstops/pull/32

**Pull request merged**
