### PR TITLE
Upgrade WakaTime plugin to v5.0.1

### PR DESCRIPTION
**Pull request by gandarez**
https://github.com/wakatime/notepadpp-wakatime/blob/master/HISTORY.rst#500-2002-12-04

### CODE REVIEW

**Comment by gandarez** [comment]
Why it's still showing `4.2.3` on plugins admin?

**Comment by modem7** [comment]
> Why it's still showing `4.2.3` on plugins admin?

The plug-in list hasn't been released. I assume once there's a new release, it'll be available.

**Comment by chcg** [comment]
@gandarez The pluginlist is just updated together with N++ releases. So you need to wait for N++ 8.4.8 release which is currently in preparation.

**Comment by gandarez** [comment]
I thought you could make it available apart any release of npp and would be much more inteligente way to keep it up-to-date.

**Comment by chcg** [comment]
Mainly an issue of the necessary hosting platform to providing the list updates.

**Pull request merged**
