### PR TITLE
Updated Npp Highlighter plug-in to version 1.0.0.1

### PR DESCRIPTION
**Pull request by michaelxzhang**
Fixed some issues.

### CODE REVIEW

**Comment by rdipardo** [comment]
@chcg, this PR was the [second time][0] in [a row][1] that SQLinFormNpp was unreachable:

    HTTPSConnectionPool(host='www.sqlinform.com', port=443):
    Max retries exceeded with url: /npp/SQLinFormNpp64_5.3.35.zip (
    Caused by SSLError(SSLCertVerificationError(
        1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
        unable to get local issuer certificate (_ssl.c:992)')))

I can reproduce locally, and the problem doesn't appear to be the certificate:

sql-in-form-cert

Looks like the plugin host is simply gone:

Fehler-403

~~~sh-session
$ nslookup https://www.sqlinform.com/npp 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find https://www.sqlinform.com/npp: NXDOMAIN
~~~

[0]: https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/45699871/job/bthr92j7ht00d4r8/messages
[1]: https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/45685196/job/o7raysj78np4flkm/messages

**Comment by donho** [comment]
@chcg 
https://github.com/notepad-plus-plus/nppPluginList/commit/e4fa23f11af9c884017e6ba8362fbf94aab54f87 has always the problem of CI for x64 & arm64 - have you any idea about the problem?

**Comment by donho** [comment]
@chcg 
I tried to rebuid https://github.com/notepad-plus-plus/nppPluginList/commit/e6585dccbd07d6073c6389e5adc9b061d1887afc, which passed, now it has the same build result of https://github.com/notepad-plus-plus/nppPluginList/commit/e4fa23f11af9c884017e6ba8362fbf94aab54f87.
I think it's related with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12636. @ArkadiuszMichalski any thought ?

**Comment by rdipardo** [comment]
@donho, at the risk of [repeating myself]: the SQLinForm [host website] is down.

~~~sh-session
$ curl -LO https://www.sqlinform.com/npp/SQLinFormNpp64_5.3.35.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
~~~

There's no ARM build of SQLinForm, so of course that job is not affected.

[repeating myself]: https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1354383280
[host website]: https://www.sqlinform.com/npp/

**Comment by ArkadiuszMichalski** [comment]
@donho 

As suggested above looks like server of this files was unavailable. Now it works:

https://www.sqlinform.com/npp/SQLinFormNpp64_5.3.35.zip
https://www.sqlinform.com/npp/SQLinFormNpp_5.3.35.zip

**Comment by donho** [comment]
@rdipardo 
> at the risk of [repeating myself](https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1354383280): the SQLinForm [host website](https://www.sqlinform.com/npp/) is down.

As I mentioned here:
https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1355565679

I run a passed commit (it was green check) again, now it doesn't pass any more (red cross).
So for me it's rather an env problem than the problem of this PR (server availability).

**Comment by ArkadiuszMichalski** [comment]
@donho 

Something is wrong with the certificate for this server.
[https://www.sqlinform.com](https://www.sqlinform.com/npp/SQLinFormNpp64_5.3.35.zip)

Do these files work for you through browsers?
https://www.sqlinform.com/npp/SQLinFormNpp64_5.3.35.zip
https://www.sqlinform.com/npp/SQLinFormNpp_5.3.35.zip

**Comment by ArkadiuszMichalski** [comment]
I don't know how certificates work exactly but looks like this site get new cert (old probably expired - not valid). Info from Chrome:

New date: 28.11.2022
Valid until: 26.02.2023

New certi package  don't like this new cert. 
Old certi package also not work because this site has new crt and checking does not match.

image

**Comment by donho** [comment]
@rdipardo & @ArkadiuszMichalski 

You're right about it. I thought the server problem that you talked about is due to this PR, and I did try to run the previous commit CI have failed result - that made me to have a bad judgement. 
After #547 which removed all the entries of SQLinForm, the result of CI is back to OK.

Thank you for your help!

**Comment by donho** [comment]
> I don't know how certificates work exactly but looks like this site get new cert (old probably expired - not valid). Info from Chrome:
> 
> New date: 28.11.2022 Valid until: 26.02.2023
> 
> New [certifi](https://pypi.org/project/certifi/) package don't like this new cert. Old [certifi](https://pypi.org/project/certifi/) package also not work because this site has new crt and checking does not match.

Yep, it's the certificate of server side, that we can do nothing about it.
SQLinForm will be removed temporarily, until their server certificate problem is solved. I'll ping the author about this issue.

**Comment by guidomarcel** [comment]
Hi, this is Guido, the author of SQLinForm. The provider of my webspace did some changes last week. First I will try to understand the issue and then contact the provider. Could you please help me and let me know what the issue is from your point of view.
Regards
Guido

**Comment by chcg** [comment]
@guidomarcel 
It seems to be an issue of the python env of appveyor used to validate the download and integrity of the plugin zip packages. The necessary root certificate seems to be not known.
On github action the check is running without problems.

**Comment by donho** [comment]
@guidomarcel 
Here's the whole error message:
HTTPSConnectionPool(host='www.sqlinform.com', port=443): Max retries exceeded with url: /npp/SQLinFormNpp64_5.3.35.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

**Comment by rdipardo** [comment]
### FYI
I can no longer reproduce locally:

~~~sh-session
$ curl -LO https://www.sqlinform.com/npp/SQLinFormNpp64_5.3.35.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  266k  100  266k    0     0   182k      0  0:00:01  0:00:01 --:--:--  182k

$ ll *.zip
-rw-r--r-- 1 rob rob 273341 Dec 18 23:43 SQLinFormNpp64_5.3.35.zip

$ python3 --version -V
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

$ python3 -m pip list | grep -E "^(attr|certifi|charset|idna|jsonschema|pyrsistent|pywin|request|urllib)"
attrs               22.1.0
certifi             2022.12.7
charset-normalizer  2.1.1
idna                3.4
jsonschema          4.16.0
pyrsistent          0.18.1
pywin32             304
requests            2.28.1
urllib3             1.26.12
~~~

The host's new certificate (since Saturday) probably did the trick:

sqlinform com-2022-12-18_23-58-43

In the future, these flukes can be worked around with kludge like this:

~~~diff
--- a/validator.py
+++ b/validator.py
@@ -143,7 +143,8 @@ def parse(filename):
             print(f' *** REQUIRES Npp {req_npp_version.strip()} ***')

         try:
-            response = requests.get(plugin["repository"])
+            skip_cert = (not plugin["display-name"].lower().startswith('sqlinform'))
+            response = requests.get(plugin["repository"], verify=skip_cert)
         except requests.exceptions.RequestException as e:
             post_error(str(e))
             continue
~~~

Only drawback is a verbose warning message.

    ~\python\3.11\Lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning:
    Unverified HTTPS request is being made to host 'www.sqlinform.com'.
    Adding certificate verification is strongly advised.
    See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

**Comment by guidomarcel** [comment]
Hi @donho , @chcg , @rdipardo ,
many thanks for your feedback. Together with my new provider (they acquired my old provider and migrated my site to a new server) we installed a new certificate on Saturday and also added a .htaccess file to the /npp folder. It should work now again. If I understand correctly @rdipardo is confirming by writing "_The host's new certificate (since Saturday) probably did the trick_".
My question: What do I need to do to re-activate the SQLinForm plugin?
Regards
Guido

**Comment by guidomarcel** [comment]
Hi @donho, am I allowed to do the updates directly in the master branch?
REgards
Guido

**Comment by donho** [comment]
@guidomarcel 
Please create a new PR for restoring the plugin.
If the CI passes I will merge your PR.

**Pull request merged**
