### PR TITLE
Update for RegexTrainer ver 1.1.0

### PR DESCRIPTION
**Pull request by ahmoylaw**
Hi Admin,

I have updated both pl.x64.json and pl.x86.json to include an update for RegexTrainer from 1.0.0 to 1.1.0

Thanks,
Ahmoy Law

### CODE REVIEW

**Comment by chcg** [comment]
Typically binary releases are published under https://github.com/ahmoylaw/RegexTrainer-Descriptions/releases.

**Comment by ahmoylaw** [comment]
Hi admin,Many thanks for your input. Very obvious that I don’t know how to use github much. Will try to update the Release page soon.From,LawOn Sep 22, 2023, at 4:54 PM, chcg ***@***.***> wrote:﻿
Typically binary releases are published under https://github.com/ahmoylaw/RegexTrainer-Descriptions/releases.

**Comment by RBDevils** [comment]
Hi Admin,
I don't know if this is the right place to write but i have 2 suggestions:
1. it's possible use RegExTrainer in all the open documents at the same time?
2. It's possible to copy and paste only the result of the group?
image

Regards,
Marco

**Comment by chcg** [comment]
@RBDevils You could add feature requests for this plugin at https://github.com/ahmoylaw/RegexTrainer-Descriptions/issues

**Pull request merged**
