### PR TITLE
Release of IndentByFold v0.7.2

### PR DESCRIPTION
**Pull request by ffes**
It now includes a 64-bit version of the plugin as well

### CODE REVIEW

**Comment by chcg** [comment]
@ffes Indent By Fold: Unexpected DLL version. DLL is 0.7.1.0 but expected 0.7.2.0

So the dll version in the rc file needs to be updated also :-(

**Comment by ffes** [comment]
Sorry, I screwed up 😢

I will fix it properly and release v0.7.3 ASAP

**Comment by chcg** [comment]
https://github.com/ffes/indentbyfold/blob/master/Version.h needs to be incremented.

**Comment by ffes** [comment]
Correct, already have code to get all the version information from the repository. Hopefully later today I have time to commit everything and update this PR

**Comment by ffes** [comment]
I just release the new version with the fixed version numbers in the DLLs. And I updated this PR accordingly

**Pull request merged**
