### PR TITLE
Update AnalysePlugin to v1.12-R43

### PR DESCRIPTION
**Pull request by mattesh**
In Version 1.12 are new features like:
 - grouping patterns
 - identifying what pattern did match in selected line
 - saving results in rtf document including background colors
 - modifying columns in pattern list
 - number of hits per pattern
 - enabling word wrap in results
 - custom colors persistent over sessions

Synced with NPP code 7.8.2
See more details and fixed bugs in changes.txt

### CODE REVIEW

**Comment by chcg** [comment]
@mattesh Could you please rebase your master, so just the real change is visible here. Do you want to change the description back to the older version?
"Helps you to search... ->"AnalysePlugin will help you to search

**Comment by mattesh** [comment]
Hi chcg,
sorry for inconvenience I understood merge is good enough for pull requests.
I'll take it back and improve.
I'll give a new change description with new pull request.
Best regards, Mattes

**Comment by mattesh** [comment]
Pls. let me know if changes are fine ;-)
I'm not that familiar with github web interface and just guess that the rebase reached the pull request ...
Thx, Mattes

**Comment by mattesh** [comment]
Sorry for spam,
shall I update also npp-plugins-x64 ? Seems to be untouched since 5/19
Thx, for your great support.
Rgds, Mattes

**Comment by chcg** [comment]
@mattesh PluginManager is just available for N++ versions before v7.5.9. Afterwards it got incompatible, see https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.12. As you updated your plugin to be based on a newer N++ version I think it might not make much sense to add it to the older PM system. Do you agree?

**Comment by mattesh** [comment]
@chcg Ok fine; just wanted to let you know that you and Dave did a great wonderful job with the plugin manager and contributed a lot to the success of N++ over the last (close to) decade :-)
Looking forward to work together.
Regards, Mattes

**Pull request merged**
