### PR TITLE
ComparePlus 1.0.0 (initial release)

### PR DESCRIPTION
**Pull request by pnedev**

### CODE REVIEW

**Comment by pnedev** [comment]
Hello @donho ,

Can I ask you to merge this PR and include it in the Plugins list coming with the new Notepad++ v8.4.5 if it is not too late for that ?
Thank you.

BR

**Comment by chcg** [comment]
@pnedev Do you think the Compare plugin is outdated now and can be removed in favour of ComparePlus?

**Comment by pnedev** [comment]
@chcg ,
I was thinking of leaving Compare plugin as it is for now. I am not its original author and I also don't know if some users won't prefer it over ComparePlus.
That is why I made the new plugin as a fork because the changes become so many and also incompatible with the old approach.
We could remove it at a later stage if it is no longer compatible with future Notepad++ versions.
If you think it is better to remove it now I don't really mind.
What do you think?

**Comment by chcg** [comment]
@pnedev That sounds reasonal to remove it just if it gets incompatible.

**Pull request closed without merging**
