### PR TITLE
Upgrade WakaTime plugin to v5.1.0

### PR DESCRIPTION
**Pull request by gandarez**
https://github.com/wakatime/notepadpp-wakatime/blob/master/HISTORY.rst#510-2023-01-07

### CODE REVIEW

**Comment by chcg** [comment]
@gandarez Please check artifact for x64. It is https://github.com/wakatime/notepadpp-wakatime/releases/download/5.1.0/WakaTime-5.1.0-x64.zip.zip instead of https://github.com/wakatime/notepadpp-wakatime/releases/download/5.1.0/WakaTime-5.1.0-x64.zip

**Comment by gandarez** [comment]
@chcg thanks for the heads up! It's fixed.

**Comment by gandarez** [comment]
Should I open another PR?

**Comment by chcg** [comment]
@gandarez I did the revert of the revert on master.

**Pull request merged**
