### PR TITLE
added multiple plugins

### PR DESCRIPTION
**Pull request by chcg**
from https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins64.xml

- 3P - Progress Programmers Pal
- Code alignment
- Code::Stats
- Compare
- CsvQuery
- Customize Toolbar
- HTML Tag

### CODE REVIEW

**Comment by chcg** [comment]
- TBD: corresponding update for x86 
- Issues seen with this update:
1, 3P is not properly removed
2, Code alignment unzip is not correct. CodeAlignment.Common.dll has size zero, also this is not the case within the zip package, seems there is some issue with the zip algorithm of wingup.
3, See description of HTML Tag. Displaying UTF8 chars is not supported properly in PA output.

**Comment by chcg** [comment]
Currently fails with:

```
Time Elapsed 00:00:04.31
cd ..
python validator.py
invalid json: 'utf8' codec can't decode byte 0xe9 in position 42: invalid continuation byte
Traceback (most recent call last):
  File "validator.py", line 12, in <module>
    parse("src/pl.x64.json")
  File "validator.py", line 9, in parse
    raise -2
TypeError: exceptions must be old-style classes or derived from BaseException, not int
Command exited with code 1
```

Seems to be something like:
https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file/14870531#14870531
I will try to fix it.

**Comment by dinkumoil** [comment]
@chcg 

I've already reported [here](https://notepad-plus-plus.org/community/topic/16566/support-for-plugins-admin-npppluginlist) a related issue.

Before adding data of _HTML Tag_ plugin there has been no character in the plugin list file which required UTF-8 encoding. Thus Notepad++ set encoding to ANSI when I was editing the file. But Npp Plugin Admin was not able to parse that file becaue it needs UTF-8 or UTF-8 BOM encoding.

After your PR including _HTML Tag_ plugin has been merged to the master branch using UTF-8 encoding, the file would be OK. But after removing the _HTML Tag_ plugin someday there would be the risc that the file encoding would fall back to ANSI again. Therefore I vote for converting plugin list files to UTF-8 BOM.

**Comment by chcg** [comment]
Fixed the issue with utf-8 input by using python3 instead of default python 2.7 which would need further code to support encoding parameter on file open.
See https://ci.appveyor.com/project/chcg/npppluginlist/builds/20062959.

Unfortunately this repo is not yet connected to appveyor to show the build status here. Needs to be added via https://ci.appveyor.com/projects/new.

**Comment by donho** [comment]
While try to get this PR merged, I've got the following message:
```
$ git pull https://github.com/chcg/nppPluginList.git multiple_plugins
warning: no common commits
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 97 (delta 20), reused 34 (delta 19), pack-reused 61
Unpacking objects: 100% (97/97), done.
From https://github.com/chcg/nppPluginList
 * branch              multiple_plugins -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

Do you use always the same branch?

**Comment by chcg** [comment]
@donho Hi, I create different branches. What I did with this one is to modify the existing branch due to the issue with the unicode sign. Therefore I did an amend commit. But that way I also did it for the appveyor branch https://github.com/chcg/nppPluginList/tree/appveyor.

I could also create a new branch and add this data if that would be easier.

**Comment by donho** [comment]
@chcg Could you please remove the unzipped 0 length plugin? 
I know it's a bug in wingup, and I'll fix it in the future version. but before fixing it, I think it's better to not include it.
Please do a new branch from the master, then apply your modification for a new PR.

**Comment by donho** [comment]
@chcg Just tried with GUp v5.0.5, Code alignment unzip works fine for me.

**Pull request closed without merging**
