### PR TITLE
Remove SQLinForm for fixing CI

### PR DESCRIPTION
**Pull request by donho**
Ref:
https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1354383280

### CODE REVIEW

**Comment by ArkadiuszMichalski** [comment]
Alternatively, we can make an exception for just this plugin plugin so that the certificate is not checked (at least for a while). I note that in Chrome I don't see a problem with this page certificate, so apparently there are some problems on the `certifi` lib side.

**Comment by donho** [comment]
@guidomarcel
Due to SQLinFormNpp causes NppPluginList CI failure (ref: https://github.com/notepad-plus-plus/nppPluginList/pull/545#issuecomment-1354383280), it will be removed temporarily. Feel free to add it back when the problem of server is solved from your side.

**Comment by donho** [comment]
@ArkadiuszMichalski 
> Alternatively we can make an exception for this one plugin

Yes we could, but for one plugin it's easy to managed (I don't even check how to do it), for several plugins it will be difficult. I prefer that the problem can be solved from their side, then we integrate it back.
We

**Comment by ArkadiuszMichalski** [comment]
https://github.com/notepad-plus-plus/nppPluginList/pull/548

I'm waiting for build result.

**Comment by donho** [comment]
@ArkadiuszMichalski 
OK, I wait for the result.
But again, I'm not for managing such problem from our side.
Even your script is working, SQLinFormNpp will be removed (temporarily).

**Comment by donho** [comment]
@ArkadiuszMichalski 
Obviously it doesn't work. Do you still want to try somethings or I can merge this PR into master?

**Comment by ArkadiuszMichalski** [comment]
Merge, the easiest way is to remove it.

**Pull request merged**
