### PR TITLE
Update AutoCodepage and AutoEolFormat plugin and add CustomLineNumbers plugin

### PR DESCRIPTION
**Pull request by dinkumoil**
@donho 

I know, there are more changes than those related to my plugins. But I want to ask you nervertheless to accept this PR. The other changes are only removing/adding spaces to achieve a consistent file content.

I use a completely automated workflow for plugin deployment and my tool to patch JSON files has removed/added the space characters in question.

### CODE REVIEW

**Comment by chcg** [comment]
@dinkumoil Looks ok to me. I also thought about the additional space for the author.

**Comment by dinkumoil** [comment]
@chcg 
 
> May I ask for the reason to move from github to sourceforge for deployment?

I love detailed statistics and I like it to see in which countries my plugins are used. :) As far as I know GitHub only provides a cumulated download statistic whereas SourceForge statistics are on a per-day basis.

**Comment by donho** [comment]
@dinkumoil  There are ALWAYS conflicts while merging your PR: 
```
$ git merge --no-ff dinkumoil-master
Auto-merging src/pl.x86.json
CONFLICT (content): Merge conflict in src/pl.x86.json
Auto-merging src/pl.x64.json
CONFLICT (content): Merge conflict in src/pl.x64.json
Automatic merge failed; fix conflicts and then commit the result.
```
Could you check if your repository is updated?

**Comment by dinkumoil** [comment]
@donho 

Yesterday I deleted my fork of your `nppPluginList` repository and created a new fork. I've used this new fork to commit my changes and to do the PR in question here. So yes, my repo _should_ have been up to date.

After you've accepted the PR of @chcg it was not, of course. I did a rebase but now my fork is completely messed up. I will close this PR, delete my fork, create a new fork to commit my changes and create a new PR.

**Comment by dinkumoil** [comment]
@donho 

My fork is deleted now and I've created another one but still all is messed up. Therefore I've deleted my last fork too, currently I don't have a fork. The [graph](https://github.com/notepad-plus-plus/nppPluginList/network) of your `nppPluginList` repo still contains a section for me and a chaotic course of my (currently not existing) fork.

I have nearly no experience with Git (I use SVN normally) so I don't understand the current situation and don't know what to do now. Please help.

**Comment by dinkumoil** [comment]
@donho 

I noticed just now that in your repository of `nppPluginList` all changes I wanted to commit are already included. Why that? I'm completly confused...

Nevertheless, the graph of your repo shows that I have two forks (I **have had** them, now they are both deleted). Deleting a forked repository doesn't make GitHub to forget it completely. I'm trapped in a "ghost fork" or something like that. As I alredy said , I don't understand the current situation and even don't know **who is able** to solve the problem: Me, you or GitHub support.

If I create a new fork of your repo, change something and create a PR, Git always merges the changes from the old (already deleted) forks to my PR (you can see it in the commit message of the merge point marked below, it was created automatically), I guess that's the reason for the conflicts you got.

grafik

**Comment by donho** [comment]
> Nevertheless, the graph of your repo shows that I have two forks (I have had them, now they are both deleted). Deleting a forked repository doesn't make GitHub to forget it completely. 

I guess there's no way for git(hub) to know the forks are deleted.

> I use SVN normally and do all operations on GitHub with my SVN client

The best way for you will be use git client directly when you work on git.
In the meantime, just do your PR as before. I will merge them manually - it will be under my name though.

**Comment by donho** [comment]
@dinkumoil  I just tried to merge your PR manually:
https://github.com/notepad-plus-plus/nppPluginList/pull/14/files
and I realized there's no change from the current master to your PR.

Could you check it and confirm me about that?

**Comment by dinkumoil** [comment]
@donho 

> I realized there's no change from the current master to your PR.

Yes, I've already noticed that (see the first sentence of my comment above). But I **definitely** made changes, the GitHub diff viewer shows them in the view of the files changed by my PR (see https://github.com/notepad-plus-plus/nppPluginList/pull/14/files).

* I changed the hosting provider for my plugins from GitHub to SourceForge.
* I have compiled a new version of my plugins which can deal with the new hosting model.
* The new versions have higher version numbers in order to trigger updates at users site from the current versions installed with the old Plugin Manager (which can not handle the new plugin hosting model) to the new ones for Plugin Admin.

I figured out right now that the changes have been committed to your repo with [your commit b5cb497eb20afef933d89f1d71ff2720b02a71c8](https://github.com/notepad-plus-plus/nppPluginList/commit/b5cb497eb20afef933d89f1d71ff2720b02a71c8).

**Comment by donho** [comment]
OK, so there's no more change from you so far right?
FYI, a new (the 1st) release of NppPluginList has been done few hours ago. So it will go into Notepad++ 7.6 release in several hours.

**Comment by dinkumoil** [comment]
Thank you for resolving the problem with the botchy forks.

> there's no more change from you

No, I have no more changes.


> Notepad++ 7.6 release in several hours

I stay tuned. :+1:

**Pull request closed without merging**
