### PR TITLE
upgrade SQLinForm to 5.3.25

### PR DESCRIPTION
**Pull request by guidomarcel**
upgrade SQLinForm to 5.3.25

### CODE REVIEW

**Comment by guidomarcel** [comment]
I got the message "All checks failed".
The 2 screenshots are attached
ci_1
ci_2

**Comment by guidomarcel** [comment]
I got the message "All checks failed".
The 2 screenshots are attached
ci_1
ci_2

**Comment by chcg** [comment]
See https://ci.appveyor.com/project/donho/npppluginlist-yy2vy/builds/23140790/job/lav4mrpoqj09fedp/messages:

> SQLinForm: Invalid hash. Got 079a9a9698092c63c69a78bb62d0360818a4386c99f2015abb5490dd734a383c but expected c93a61098ab095e6e912697abe9945b095b9c3e8a701b8cedaa95dbaf38db20e

**Comment by chcg** [comment]
Replaced by #69

**Pull request closed without merging**
