### PR TITLE
update HTMLTag to 1.2.0

### PR DESCRIPTION
**Pull request by rdipardo**
Also:
  * update repository
  * update download URLs

Reason for change of repo ownership:
* https://sourceforge.net/p/npp-plugins/discussion/725650/thread/08c8e87447/
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1028188095

### CODE REVIEW

**Comment by Yaron10** [comment]
@rdipardo,

I've just seen this PR (your reference in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104).

Congratulations!
I've manually downloaded the ZIP file from your repo on bitbucket.
Great work. Thank you very much. 👍 

***
May I ask why the extension of the NEWS and README files is "textile" instead of "txt"?

**Comment by donho** [comment]
@rdipardo 
It seems the build is OK now.

**Comment by rdipardo** [comment]
@Yaron10,
> May I ask why the extension of the NEWS and README files is "textile" instead of "txt"?

<https://textile-lang.com>

**Comment by chcg** [comment]
@rdipardo Thanks for taking over the maintenance of this plugin.
@Yaron10 Thanks for supporting.

**Pull request merged**
